### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by lampdanny** [mantisbt-plugins/LinkedCustomFields#10]
Problem: linked fields with special characters (like &) can't be saved
Solution: use htmlspecialchars_decode in LinkedCustomFields.API.php

	static function getLinkedFieldId( $p_source_field_id ) {

		$t_query = "SELECT target_field_id FROM " . plugin_table( 'data' ) . " WHERE custom_field_id = " . db_param();

		$t_result = db_query( $t_query, array( $p_source_field_id ) );

		if( 0 == db_num_rows( $t_result ) ) {
			return null;
		}

		$t_array = db_fetch_array( $t_result );
		**return htmlspecialchars_decode($t_field_values_js);**
	}

**Comment by dregad** [comment]
Would you be able to submit a pull request ?

**Comment by lampdanny** [comment]
> Would you be able to submit a pull request ?

Probably. New to Github ...

**Comment by dregad** [comment]
Thanks. Let me know if you need help
