### ISSUE TITLE
How can I change the access level in Configure custom field links? 

### ISSUE THREAD

**Issue by tyro008** [mantisbt-plugins/LinkedCustomFields#13]
On my current installation, only the administrator account can Configure custom field links. Is it possible to allow the manager account to do the same?

**Comment by dregad** [comment]
Access control is based on MantisBT global config option *manage_custom_fields_threshold* which indeed by default is set to ADMINISTRATOR. You're free to change that to MANAGER (but of course that will let Managers create/modify custom fields).

I personally don't think it's worth the effort to create a specific access level to allow managing CF links independently from the custom fields themselves. If this feature is important to you, feel free to contribute with a pull request.

**Comment by tyro008** [comment]
I don't want the Managers to create/modify custom fields. If I can't independently set the Configure custom field links access, is there a way to hide the Configure custom field links tab on the Manage page? 
![image](https://github.com/mantisbt-plugins/LinkedCustomFields/assets/73383565/77610ace-879e-4140-83cf-f95887f3e6ac)
