### ISSUE TITLE
Mapping section is not displayed

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/LinkedCustomFields#4]
Stuck at `Loading Custom Field data, please wait...`

Browser console shows errors
![image](https://user-images.githubusercontent.com/449891/154850941-9df8e502-6d6e-4a82-8517-1ce72363a83e.png)

Error occurs when MantisBT is not installed at `/mantis`, caused by a hardcoded path in config.js on line 35.

[Originally reported](https://gitter.im/mantisbt/mantisbt?at=6210fe626b91242320f81b6b) by @CasN

**Comment by Maximus48p** [comment]
It seems that this problem stil exits. 
My root folder is called different and the plugin folder is outside the root folder.
Please tell me how to fix? thx!

**Comment by dregad** [comment]
@Maximus48p More info is needed to troubleshoot. Details on your installation (tree structure and relevant config_inc.php settings), as well any errors you're seeing - If it's the same problem, there should be something in the browser console.

**Comment by Maximus48p** [comment]
Have to say it only occurs in my test environment. Need to do some more digging what is different. thx
